# Generated by Django 2.1.4 on 2018-12-11 06:52

from django.db import migrations, models
import django.db.models.deletion
import register.constants


class Migration(migrations.Migration):

    dependencies = [("matching", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="secretsantagroup",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="owner",
            name="secret_santa_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="matching.SecretSantaGroup",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="state",
            field=models.CharField(
                choices=[
                    (register.constants.MessageStates("initial"), "initial"),
                    (register.constants.MessageStates("foundation"), "foundation"),
                    (register.constants.MessageStates("name"), "name"),
                    (register.constants.MessageStates("forwarding"), "forwarding"),
                ],
                default="initial",
                max_length=20,
            ),
        ),
    ]
