# Generated by Django 2.1.4 on 2018-12-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("matching", "0003_messages")]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="sender",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="matching.Owner",
            ),
        )
    ]
