# Generated by Django 2.1.4 on 2018-12-11 07:27

from django.db import migrations, models
import django.db.models.deletion
import register.constants


class Migration(migrations.Migration):

    dependencies = [("matching", "0004_auto_20181211_0706")]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="excluded_from_matching_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="_owner_excluded_from_matching_with_+",
                to="matching.Owner",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="foundation_message",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="owner_name",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="secret_santa_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="matching.SecretSantaGroup",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="state",
            field=models.CharField(
                choices=[
                    ("initial", register.constants.MessageStates("initial")),
                    ("foundation", register.constants.MessageStates("foundation")),
                    ("name", register.constants.MessageStates("name")),
                    ("forwarding", register.constants.MessageStates("forwarding")),
                ],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="your_secret",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="matching.Owner",
            ),
        ),
    ]
