# Generated by Django 2.1.4 on 2018-12-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_auto_20181211_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='secret_santa_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='matching.SecretSantaGroup'),
        ),
    ]
