# Generated by Django 2.1.4 on 2018-12-14 06:35

from django.db import migrations, models
import matching.models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20181214_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='your_secret',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=matching.models.ALSO_CLEAR_YOUR_SECRET, to='matching.Owner'),
        ),
    ]
