# Generated by Django 2.1.4 on 2018-12-14 06:41

from django.db import migrations, models
import django.db.models.deletion
import matching.models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_auto_20181214_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='secret_santa_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=matching.models.ALSO_CLEAR_YOUR_SECRET, to='matching.SecretSantaGroup'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='your_secret',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matching.Owner'),
        ),
    ]
