# Generated by Django 2.1.4 on 2018-12-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_auto_20181214_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='your_secret',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matching.Owner'),
        ),
    ]
