# Generated by Django 2.1.3 on 2018-12-06 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "parsed_number",
                    models.CharField(
                        max_length=12, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("raw_number", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="VerificationAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("hash", models.CharField(max_length=64)),
                ("twilio_sid", models.CharField(max_length=64)),
                (
                    "number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="verification_attempts",
                        to="register.PhoneNumber",
                    ),
                ),
            ],
        ),
    ]
