# Generated by Django 2.1.4 on 2018-12-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationattempt',
            name='number',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verification_attempts', to='register.PhoneNumber'),
        ),
    ]
